### ISSUE TITLE
Support changing working directory

### ISSUE THREAD

**Issue by itamarst** [drone-plugins/drone-pypi#23]
If the Python package + setup.py is in a subdirectory, you need to be able to `cd` into that directory for packaging to work correctly. E.g.

```
mypythonapp/
    setup.py  # for packaging `mypackage`
    mypackage/
        __init__.py
```

Merely giving the path to `setup.py` won't work, you need to change working directory to `mypythonapp` before running setup.py sdist.

**Comment by tboerger** [comment]
@xoxys maybe you are interested in doing that? :)

**Comment by goodspark** [comment]
I'm running into this problem too. I have a repo that's meant to build libraries for multiple languages and want to use DroneCI to release Python packages. This fails for me. The version number is wrong and the files that are packaged are wrong as well (taken from the repo's root dir and not the dir where setup.py is located).

**Comment by tboerger** [comment]
You are able to configure the dist directory now:

```
settings:
  dist_dir: mypythonapp/
```
